[versions]
build-namespace = "com.gasparaitis.owncommunity"
build-code = "1"
build-name = "0.0.1"
build-testInstrumentationRunner = "androidx.test.runner.AndroidJUnitRunner"
build-sdk-min = "24"
build-sdk-compile = "33"
build-sdk-target = "33"

activity-compose = "1.7.2"
agp = "8.1.0-rc01"
androidx-test-ext-junit = "1.1.5"
compose-bom = "2023.06.01"
compose-compiler = "1.4.8"
compose-destinations-core = "1.9.42-beta"
compose-destinations-ksp = "1.9.42-beta"
core-ktx = "1.10.1"
espresso-core = "3.5.1"
gms = "4.3.15"
junit = "4.13.2"
kotlin = "1.8.22"
ksp = "1.8.22-1.0.11"
lifecycle-runtime-ktx = "2.6.1"
material = "1.4.3"

[libraries]
compose-compiler = { module = "androidx.compose.compiler:compiler", version.ref = "compose-compiler" }
compose-destinations-core = { module = "io.github.raamcosta.compose-destinations:core", version.ref = "compose-destinations-core" }
compose-destinations-ksp = { module = "io.github.raamcosta.compose-destinations:ksp", version.ref = "compose-destinations-ksp" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-test-ext-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }
lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycle-runtime-ktx" }
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose" }
compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "compose-bom" }
ui = { group = "androidx.compose.ui", name = "ui" }
ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
material = { module = "androidx.compose.material:material", version.ref = "material" }
material3 = { group = "androidx.compose.material3", name = "material3" }

[plugins]
com-android-application = { id = "com.android.application", version.ref = "agp" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

[bundles]

