name: Android CD

on:
    push:
        branches: [ "main" ]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

jobs:
    uploadToPlayStore:
        name: Upload to Play Store
        needs: [buildAndTest]
        runs-on: ubuntu-latest

        steps:
            - name: Check out code
              uses: actions/checkout@v3
            - name: Set up JDK 17
              uses: actions/setup-java@v3
              with:
                  java-version: '17'
                  distribution: 'temurin'
                  cache: gradle
            - name: Build .aab
              run: ./gradlew bundleRelease
            - name: Upload Android Release to Play Store
              uses: r0adkll/upload-google-play@v1
              with:
                  serviceAccountJsonPlainText: ${{ secrets.GOOGLE_SERVICES_JSON }}
                  packageName: dk.tv2.vejr
                  releaseFiles: ${{ github.workspace }}/app/build/outputs/bundle/release/app-release.aab
                  track: internal
                  status: completed
