name: Android CD

on:
    push:
        branches: [ "main" ]

jobs:
    uploadToPlayStore:
      name: Upload to Play Store
      runs-on: ubuntu-latest

      steps:
          - name: Check out code
            uses: actions/checkout@v3
          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
                java-version: '17'
                distribution: 'temurin'
                cache: gradle
          - name: Grant execute permission for gradlew
            run: chmod +x gradlew
          - name: Create google-services.json
            run: cat /home/runner/work/owncommunity/owncommunity/app/google-services.json | base64
          - name: Populate google-services.json
            env:
              DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
            run: echo $DATA > /home/runner/work/owncommunity/owncommunity/app/google-services.json
          - name: Build .aab
            run: ./gradlew bundleRelease
          - name: Upload Android Release to Play Store
            uses: r0adkll/upload-google-play@v1
            with:
                serviceAccountJsonPlainText: ${{ secrets.SERVICE_ACCOUNT_JSON }}
                packageName: com.gasparaiciukas.owncommunity
                releaseFiles: ${{ github.workspace }}/app/build/outputs/bundle/release/app-release.aab
                track: internal
                status: completed
